version: "3.3"
services:
    neo4j:
        image: neo4j:latest
        volumes:
            - type: volume
              source: neo4j_data
              target: /data
            - type: volume
              source: neo4j_logs
              target: /logs
        ports:
            - 7474:7474
            - 7687:7687
volumes:
    neo4j_data:
    neo4j_logs:                
