version: "3.3"
services:
    neo4j:
        image: neo4j:latest
        volumes:
            - $HOME/neo4j/data:/data
            - $HOME/neo4j/logs:/logs
        ports:
            - 7474:7474
            - 7687:7687
