version: "3.3"
services:
    neo4j:
        image: neo4j:latest
        volumes:
            - $HOME/neo4j/data:/data
            - $HOME/neo4j/logs:/logs
            - $HOME/neo4j/import:/import
            - $HOME/neo4j/conf:/conf
        ports:
            - 7474:7474
            - 7687:7687
        environment:
            - NEO4J_CACHE_MEMORY=4G
            - NEO4J_HEAP_MEMORY=4G
